export const GET_EVENTO_PENDING = 'GET_EVENTO_PENDING';
export const GET_EVENTO_SUCCESS = 'GET_EVENTO_SUCCESS';
export const GET_EVENTO_ERROR = 'GET_EVENTO_ERROR';

export const POST_EVENTO_PENDING = 'POST_EVENTO_PENDING';
export const POST_EVENTO_SUCCESS = 'POST_EVENTO_SUCCESS';
export const POST_EVENTO_ERROR = 'POST_EVENTO_ERROR';

export const UPDATE_EVENTO_PENDING = 'UPDATE_EVENTO_PENDING';
export const UPDATE_EVENTO_SUCCESS = 'UPDATE_EVENTO_SUCCESS';
export const UPDATE_EVENTO_ERROR = 'UPDATE_EVENTO_ERROR';

export const DELETE_EVENTO_PENDING = 'DELETE_EVENTO_PENDING';
export const DELETE_EVENTO_SUCCESS = 'DELETE_EVENTO_SUCCESS';
export const DELETE_EVENTO_ERROR = 'DELETE_EVENTO_ERROR';
