export const GET_INSPECCIONROBORUEDA_PENDING = 'GET_INSPECCIONROBORUEDA_PENDING';
export const GET_INSPECCIONROBORUEDA_SUCCESS = 'GET_INSPECCIONROBORUEDA_SUCCESS';
export const GET_INSPECCIONROBORUEDA_ERROR = 'GET_INSPECCIONROBORUEDA_ERROR';

export const POST_INSPECCIONROBORUEDA_PENDING = 'POST_INSPECCIONROBORUEDA_PENDING';
export const POST_INSPECCIONROBORUEDA_SUCCESS = 'POST_INSPECCIONROBORUEDA_SUCCESS';
export const POST_INSPECCIONROBORUEDA_ERROR = 'POST_INSPECCIONROBORUEDA_ERROR';

export const UPDATE_INSPECCIONROBORUEDA_PENDING = 'UPDATE_INSPECCIONROBORUEDA_PENDING';
export const UPDATE_INSPECCIONROBORUEDA_SUCCESS = 'UPDATE_INSPECCIONROBORUEDA_SUCCESS';
export const UPDATE_INSPECCIONROBORUEDA_ERROR = 'UPDATE_INSPECCIONROBORUEDA_ERROR';

export const DELETE_INSPECCIONROBORUEDA_PENDING = 'DELETE_INSPECCIONROBORUEDA_PENDING';
export const DELETE_INSPECCIONROBORUEDA_SUCCESS = 'DELETE_INSPECCIONROBORUEDA_SUCCESS';
export const DELETE_INSPECCIONROBORUEDA_ERROR = 'DELETE_INSPECCIONROBORUEDA_ERROR';
