export const GET_INVOLUCRADO_PENDING = 'GET_INVOLUCRADO_PENDING';
export const GET_INVOLUCRADO_SUCCESS = 'GET_INVOLUCRADO_SUCCESS';
export const GET_INVOLUCRADO_ERROR = 'GET_INVOLUCRADO_ERROR';

export const ADD_INVOLUCRADO_PENDING = 'ADD_INVOLUCRADO_PENDING';
export const ADD_INVOLUCRADO_SUCCESS = 'ADD_INVOLUCRADO_SUCCESS';
export const ADD_INVOLUCRADO_ERROR = 'ADD_INVOLUCRADO_ERROR';

export const UPDATE_INVOLUCRADO_PENDING = 'UPDATE_INVOLUCRADO_PENDING';
export const UPDATE_INVOLUCRADO_SUCCESS = 'UPDATE_INVOLUCRADO_SUCCESS';
export const UPDATE_INVOLUCRADO_ERROR = 'UPDATE_INVOLUCRADO_ERROR';

export const DELETE_INVOLUCRADO_PENDING = 'DELETE_INVOLUCRADO_PENDING';
export const DELETE_INVOLUCRADO_SUCCESS = 'DELETE_INVOLUCRADO_SUCCESS';
export const DELETE_INVOLUCRADO_ERROR = 'DELETE_INVOLUCRADO_ERROR';
