export const GET_VEHICULO_PENDING = 'GET_VEHICULO_PENDING';
export const GET_VEHICULO_SUCCESS = 'GET_VEHICULO_SUCCESS';
export const GET_VEHICULO_ERROR = 'GET_VEHICULO_ERROR';

export const POST_VEHICULO_PENDING = 'POST_VEHICULO_PENDING';
export const POST_VEHICULO_SUCCESS = 'POST_VEHICULO_SUCCESS';
export const POST_VEHICULO_ERROR = 'POST_VEHICULO_ERROR';

export const UPDATE_VEHICULO_PENDING = 'UPDATE_VEHICULO_PENDING';
export const UPDATE_VEHICULO_SUCCESS = 'UPDATE_VEHICULO_SUCCESS';
export const UPDATE_VEHICULO_ERROR = 'UPDATE_VEHICULO_ERROR';

export const DELETE_VEHICULO_PENDING = 'DELETE_VEHICULO_PENDING';
export const DELETE_VEHICULO_SUCCESS = 'DELETE_VEHICULO_SUCCESS';
export const DELETE_VEHICULO_ERROR = 'DELETE_VEHICULO_ERROR';
