export const GET_VEHICULO_PENDING = 'GET_VEHICULO_PENDING';
export const GET_VEHICULO_SUCCESS = 'GET_VEHICULO_SUCCESS';
export const GET_VEHICULO_ERROR = 'GET_VEHICULO_ERROR';

export const ADD_VEHICULO_PENDING = 'ADD_VEHICULO_PENDING';
export const ADD_VEHICULO_SUCCESS = 'ADD_VEHICULO_SUCCESS';
export const ADD_VEHICULO_ERROR = 'ADD_VEHICULO_ERROR';

export const UPDATE_VEHICULO_PENDING = 'UPDATE_VEHICULO_PENDING';
export const UPDATE_VEHICULO_SUCCESS = 'UPDATE_VEHICULO_SUCCESS';
export const UPDATE_VEHICULO_ERROR = 'UPDATE_VEHICULO_ERROR';

export const DELETE_VEHICULO_PENDING = 'DELETE_VEHICULO_PENDING';
export const DELETE_VEHICULO_SUCCESS = 'DELETE_VEHICULO_SUCCESS';
export const DELETE_VEHICULO_ERROR = 'DELETE_VEHICULO_ERROR';
