export const GET_OCURRENCELOCATION_PENDING = 'GET_OCURRENCELOCATION_PENDING';
export const GET_OCURRENCELOCATION_SUCCESS = 'GET_OCURRENCELOCATION_SUCCESS';
export const GET_OCURRENCELOCATION_ERROR = 'GET_OCURRENCELOCATION_ERROR';

export const ADD_OCURRENCELOCATION_PENDING = 'ADD_OCURRENCELOCATION_PENDING';
export const ADD_OCURRENCELOCATION_SUCCESS = 'ADD_OCURRENCELOCATION_SUCCESS';
export const ADD_OCURRENCELOCATION_ERROR = 'ADD_OCURRENCELOCATION_ERROR';

export const EDIT_OCURRENCELOCATION_PENDING = 'EDIT_OCURRENCELOCATION_PENDING';
export const EDIT_OCURRENCELOCATION_SUCCESS = 'EDIT_OCURRENCELOCATION_SUCCESS';
export const EDIT_OCURRENCELOCATION_ERROR = 'EDIT_OCURRENCELOCATION_ERROR';

export const DELETE_OCURRENCELOCATION_PENDING = 'DELETE_OCURRENCELOCATION_PENDING';
export const DELETE_OCURRENCELOCATION_SUCCESS = 'DELETE_OCURRENCELOCATION_SUCCESS';
export const DELETE_OCURRENCELOCATION_ERROR = 'DELETE_OCURRENCELOCATION_ERROR';
