export const GET_ADMINISTRATIVO_PENDING = 'GET_ADMINISTRATIVO_PENDING';
export const GET_ADMINISTRATIVO_SUCCESS = 'GET_ADMINISTRATIVO_SUCCESS';
export const GET_ADMINISTRATIVO_ERROR = 'GET_ADMINISTRATIVO_ERROR';

export const POST_ADMINISTRATIVO_PENDING = 'POST_ADMINISTRATIVO_PENDING';
export const POST_ADMINISTRATIVO_SUCCESS = 'POST_ADMINISTRATIVO_SUCCESS';
export const POST_ADMINISTRATIVO_ERROR = 'POST_ADMINISTRATIVO_ERROR';

export const UPDATE_ADMINISTRATIVO_PENDING = 'UPDATE_ADMINISTRATIVO_PENDING';
export const UPDATE_ADMINISTRATIVO_SUCCESS = 'UPDATE_ADMINISTRATIVO_SUCCESS';
export const UPDATE_ADMINISTRATIVO_ERROR = 'UPDATE_ADMINISTRATIVO_ERROR';

export const DELETE_ADMINISTRATIVO_PENDING = 'DELETE_ADMINISTRATIVO_PENDING';
export const DELETE_ADMINISTRATIVO_SUCCESS = 'DELETE_ADMINISTRATIVO_SUCCESS';
export const DELETE_ADMINISTRATIVO_ERROR = 'DELETE_ADMINISTRATIVO_ERROR';
