export const GET_ADMINISTRATIVOISTRATIVOS_PENDING = 'GET_ADMINISTRATIVOISTRATIVOS_PENDING';
export const GET_ADMINISTRATIVOISTRATIVOS_SUCCESS = 'GET_ADMINISTRATIVOISTRATIVOS_SUCCESS';
export const GET_ADMINISTRATIVOISTRATIVOS_ERROR = 'GET_ADMINISTRATIVOISTRATIVOS_ERROR';

export const ADD_ADMINISTRATIVO_PENDING = 'ADD_ADMINISTRATIVO_PENDING';
export const ADD_ADMINISTRATIVO_SUCCESS = 'ADD_ADMINISTRATIVO_SUCCESS';
export const ADD_ADMINISTRATIVO_ERROR = 'ADD_ADMINISTRATIVO_ERROR';

export const EDIT_ADMINISTRATIVO_PENDING = 'EDIT_ADMINISTRATIVO_PENDING';
export const EDIT_ADMINISTRATIVO_SUCCESS = 'EDIT_ADMINISTRATIVO_SUCCESS';
export const EDIT_ADMINISTRATIVO_ERROR = 'EDIT_ADMINISTRATIVO_ERROR';

export const DELETE_ADMINISTRATIVO_PENDING = 'DELETE_ADMINISTRATIVO_PENDING';
export const DELETE_ADMINISTRATIVO_SUCCESS = 'DELETE_ADMINISTRATIVO_SUCCESS';
export const DELETE_ADMINISTRATIVO_ERROR = 'DELETE_ADMINISTRATIVO_ERROR';
