export const GET_INVESTIGATOR_PENDING = 'GET_INVESTIGATOR_PENDING';
export const GET_INVESTIGATOR_SUCCESS = 'GET_INVESTIGATOR_SUCCESS';
export const GET_INVESTIGATOR_ERROR = 'GET_INVESTIGATOR_ERROR';

export const ADD_INVESTIGATOR_PENDING = 'ADD_INVESTIGATOR_PENDING';
export const ADD_INVESTIGATOR_SUCCESS = 'ADD_INVESTIGATOR_SUCCESS';
export const ADD_INVESTIGATOR_ERROR = 'ADD_INVESTIGATOR_ERROR';

export const EDIT_INVESTIGATOR_PENDING = 'EDIT_INVESTIGATOR_PENDING';
export const EDIT_INVESTIGATOR_SUCCESS = 'EDIT_INVESTIGATOR_SUCCESS';
export const EDIT_INVESTIGATOR_ERROR = 'EDIT_INVESTIGATOR_ERROR';

export const DELETE_INVESTIGATOR_PENDING = 'DELETE_INVESTIGATOR_PENDING';
export const DELETE_INVESTIGATOR_SUCCESS = 'DELETE_INVESTIGATOR_SUCCESS';
export const DELETE_INVESTIGATOR_ERROR = 'DELETE_INVESTIGATOR_ERROR';
