export const GET_CONSULTOR_PENDING = 'GET_CONSULTOR_PENDING';
export const GET_CONSULTOR_SUCCESS = 'GET_CONSULTOR_SUCCESS';
export const GET_CONSULTOR_ERROR = 'GET_CONSULTOR_ERROR';

export const POST_CONSULTOR_PENDING = 'POST_CONSULTOR_PENDING';
export const POST_CONSULTOR_SUCCESS = 'POST_CONSULTOR_SUCCESS';
export const POST_CONSULTOR_ERROR = 'POST_CONSULTOR_ERROR';

export const UPDATE_CONSULTOR_PENDING = 'UPDATE_CONSULTOR_PENDING';
export const UPDATE_CONSULTOR_SUCCESS = 'UPDATE_CONSULTOR_SUCCESS';
export const UPDATE_CONSULTOR_ERROR = 'UPDATE_CONSULTOR_ERROR';

export const DELETE_CONSULTOR_PENDING = 'DELETE_CONSULTOR_PENDING';
export const DELETE_CONSULTOR_SUCCESS = 'DELETE_CONSULTOR_SUCCESS';
export const DELETE_CONSULTOR_ERROR = 'DELETE_CONSULTOR_ERROR';
