export const GET_INSPECCIONSINIESTRO_PENDING = 'GET_INSPECCIONSINIESTRO_PENDING';
export const GET_INSPECCIONSINIESTRO_SUCCESS = 'GET_INSPECCIONSINIESTRO_SUCCESS';
export const GET_INSPECCIONSINIESTRO_ERROR = 'GET_INSPECCIONSINIESTRO_ERROR';

export const POST_INSPECCIONSINIESTRO_PENDING = 'POST_INSPECCIONSINIESTRO_PENDING';
export const POST_INSPECCIONSINIESTRO_SUCCESS = 'POST_INSPECCIONSINIESTRO_SUCCESS';
export const POST_INSPECCIONSINIESTRO_ERROR = 'POST_INSPECCIONSINIESTRO_ERROR';

export const UPDATE_INSPECCIONSINIESTRO_PENDING = 'UPDATE_INSPECCIONSINIESTRO_PENDING';
export const UPDATE_INSPECCIONSINIESTRO_SUCCESS = 'UPDATE_INSPECCIONSINIESTRO_SUCCESS';
export const UPDATE_INSPECCIONSINIESTRO_ERROR = 'UPDATE_INSPECCIONSINIESTRO_ERROR';

export const DELETE_INSPECCIONSINIESTRO_PENDING = 'DELETE_INSPECCIONSINIESTRO_PENDING';
export const DELETE_INSPECCIONSINIESTRO_SUCCESS = 'DELETE_INSPECCIONSINIESTRO_SUCCESS';
export const DELETE_INSPECCIONSINIESTRO_ERROR = 'DELETE_INSPECCIONSINIESTRO_ERROR';
