export const GET_LUGARROBORUEDA_PENDING = 'GET_LUGARROBORUEDA_PENDING';
export const GET_LUGARROBORUEDA_SUCCESS = 'GET_LUGARROBORUEDA_SUCCESS';
export const GET_LUGARROBORUEDA_ERROR = 'GET_LUGARROBORUEDA_ERROR';

export const POST_LUGARROBORUEDA_PENDING = 'POST_LUGARROBORUEDA_PENDING';
export const POST_LUGARROBORUEDA_SUCCESS = 'POST_LUGARROBORUEDA_SUCCESS';
export const POST_LUGARROBORUEDA_ERROR = 'POST_LUGARROBORUEDA_ERROR';

export const UPDATE_LUGARROBORUEDA_PENDING = 'UPDATE_LUGARROBORUEDA_PENDING';
export const UPDATE_LUGARROBORUEDA_SUCCESS = 'UPDATE_LUGARROBORUEDA_SUCCESS';
export const UPDATE_LUGARROBORUEDA_ERROR = 'UPDATE_LUGARROBORUEDA_ERROR';

export const DELETE_LUGARROBORUEDA_PENDING = 'DELETE_LUGARROBORUEDA_PENDING';
export const DELETE_LUGARROBORUEDA_SUCCESS = 'DELETE_LUGARROBORUEDA_SUCCESS';
export const DELETE_LUGARROBORUEDA_ERROR = 'DELETE_LUGARROBORUEDA_ERROR';
