export const GET_INVOLVED_PENDING = 'GET_INVOLVED_PENDING';
export const GET_INVOLVED_SUCCESS = 'GET_INVOLVED_SUCCESS';
export const GET_INVOLVED_ERROR = 'GET_INVOLVED_ERROR';

export const ADD_INVOLVED_PENDING = 'ADD_INVOLVED_PENDING';
export const ADD_INVOLVED_SUCCESS = 'ADD_INVOLVED_SUCCESS';
export const ADD_INVOLVED_ERROR = 'ADD_INVOLVED_ERROR';

export const EDIT_INVOLVED_PENDING = 'EDIT_INVOLVED_PENDING';
export const EDIT_INVOLVED_SUCCESS = 'EDIT_INVOLVED_SUCCESS';
export const EDIT_INVOLVED_ERROR = 'EDIT_INVOLVED_ERROR';

export const DELETE_INVOLVED_PENDING = 'DELETE_INVOLVED_PENDING';
export const DELETE_INVOLVED_SUCCESS = 'DELETE_INVOLVED_SUCCESS';
export const DELETE_INVOLVED_ERROR = 'DELETE_INVOLVED_ERROR';
