export const GET_RUEDA_PENDING = 'GET_RUEDA_PENDING';
export const GET_RUEDA_SUCCESS = 'GET_RUEDA_SUCCESS';
export const GET_RUEDA_ERROR = 'GET_RUEDA_ERROR';

export const GET_RUEDAS_PENDING = 'GET_RUEDAS_PENDING';
export const GET_RUEDAS_SUCCESS = 'GET_RUEDAS_SUCCESS';
export const GET_RUEDAS_ERROR = 'GET_RUEDAS_ERROR';

export const POST_RUEDA_PENDING = 'POST_RUEDA_PENDING';
export const POST_RUEDA_SUCCESS = 'POST_RUEDA_SUCCESS';
export const POST_RUEDA_ERROR = 'POST_RUEDA_ERROR';

export const UPDATE_RUEDA_PENDING = 'UPDATE_RUEDA_PENDING';
export const UPDATE_RUEDA_SUCCESS = 'UPDATE_RUEDA_SUCCESS';
export const UPDATE_RUEDA_ERROR = 'UPDATE_RUEDA_ERROR';

export const DELETE_RUEDA_PENDING = 'DELETE_RUEDA_PENDING';
export const DELETE_RUEDA_SUCCESS = 'DELETE_RUEDA_SUCCESS';
export const DELETE_RUEDA_ERROR = 'DELETE_RUEDA_ERROR';
