export const GET_ENTREVISTASINIESTRO_PENDING = 'GET_ENTREVISTASINIESTRO_PENDING';
export const GET_ENTREVISTASINIESTRO_SUCCESS = 'GET_ENTREVISTASINIESTRO_SUCCESS';
export const GET_ENTREVISTASINIESTRO_ERROR = 'GET_ENTREVISTASINIESTRO_ERROR';

export const POST_ENTREVISTASINIESTRO_PENDING = 'POST_ENTREVISTASINIESTRO_PENDING';
export const POST_ENTREVISTASINIESTRO_SUCCESS = 'POST_ENTREVISTASINIESTRO_SUCCESS';
export const POST_ENTREVISTASINIESTRO_ERROR = 'POST_ENTREVISTASINIESTRO_ERROR';

export const UPDATE_ENTREVISTASINIESTRO_PENDING = 'UPDATE_ENTREVISTASINIESTRO_PENDING';
export const UPDATE_ENTREVISTASINIESTRO_SUCCESS = 'UPDATE_ENTREVISTASINIESTRO_SUCCESS';
export const UPDATE_ENTREVISTASINIESTRO_ERROR = 'UPDATE_ENTREVISTASINIESTRO_ERROR';

export const DELETE_ENTREVISTASINIESTRO_PENDING = 'DELETE_ENTREVISTASINIESTRO_PENDING';
export const DELETE_ENTREVISTASINIESTRO_SUCCESS = 'DELETE_ENTREVISTASINIESTRO_SUCCESS';
export const DELETE_ENTREVISTASINIESTRO_ERROR = 'DELETE_ENTREVISTASINIESTRO_ERROR';
