export const GET_ENTREVISTAROBORUEDA_PENDING = 'GET_ENTREVISTAROBORUEDA_PENDING';
export const GET_ENTREVISTAROBORUEDA_SUCCESS = 'GET_ENTREVISTAROBORUEDA_SUCCESS';
export const GET_ENTREVISTAROBORUEDA_ERROR = 'GET_ENTREVISTAROBORUEDA_ERROR';

export const POST_ENTREVISTAROBORUEDA_PENDING = 'POST_ENTREVISTAROBORUEDA_PENDING';
export const POST_ENTREVISTAROBORUEDA_SUCCESS = 'POST_ENTREVISTAROBORUEDA_SUCCESS';
export const POST_ENTREVISTAROBORUEDA_ERROR = 'POST_ENTREVISTAROBORUEDA_ERROR';

export const UPDATE_ENTREVISTAROBORUEDA_PENDING = 'UPDATE_ENTREVISTAROBORUEDA_PENDING';
export const UPDATE_ENTREVISTAROBORUEDA_SUCCESS = 'UPDATE_ENTREVISTAROBORUEDA_SUCCESS';
export const UPDATE_ENTREVISTAROBORUEDA_ERROR = 'UPDATE_ENTREVISTAROBORUEDA_ERROR';

export const DELETE_ENTREVISTAROBORUEDA_PENDING = 'DELETE_ENTREVISTAROBORUEDA_PENDING';
export const DELETE_ENTREVISTAROBORUEDA_SUCCESS = 'DELETE_ENTREVISTAROBORUEDA_SUCCESS';
export const DELETE_ENTREVISTAROBORUEDA_ERROR = 'DELETE_ENTREVISTAROBORUEDA_ERROR';
