export const GET_RELEVADOR_PENDING = 'GET_RELEVADOR_PENDING';
export const GET_RELEVADOR_SUCCESS = 'GET_RELEVADOR_SUCCESS';
export const GET_RELEVADOR_ERROR = 'GET_RELEVADOR_ERROR';

export const POST_RELEVADOR_PENDING = 'POST_RELEVADOR_PENDING';
export const POST_RELEVADOR_SUCCESS = 'POST_RELEVADOR_SUCCESS';
export const POST_RELEVADOR_ERROR = 'POST_RELEVADOR_ERROR';

export const UPDATE_RELEVADOR_PENDING = 'UPDATE_RELEVADOR_PENDING';
export const UPDATE_RELEVADOR_SUCCESS = 'UPDATE_RELEVADOR_SUCCESS';
export const UPDATE_RELEVADOR_ERROR = 'UPDATE_RELEVADOR_ERROR';

export const DELETE_RELEVADOR_PENDING = 'DELETE_RELEVADOR_PENDING';
export const DELETE_RELEVADOR_SUCCESS = 'DELETE_RELEVADOR_SUCCESS';
export const DELETE_RELEVADOR_ERROR = 'DELETE_RELEVADOR_ERROR';
