export const GET_CONTROLADOR_PENDING = 'GET_CONTROLADOR_PENDING';
export const GET_CONTROLADOR_SUCCESS = 'GET_CONTROLADOR_SUCCESS';
export const GET_CONTROLADOR_ERROR = 'GET_CONTROLADOR_ERROR';

export const POST_CONTROLADOR_PENDING = 'POST_CONTROLADOR_PENDING';
export const POST_CONTROLADOR_SUCCESS = 'POST_CONTROLADOR_SUCCESS';
export const POST_CONTROLADOR_ERROR = 'POST_CONTROLADOR_ERROR';

export const UPDATE_CONTROLADOR_PENDING = 'UPDATE_CONTROLADOR_PENDING';
export const UPDATE_CONTROLADOR_SUCCESS = 'UPDATE_CONTROLADOR_SUCCESS';
export const UPDATE_CONTROLADOR_ERROR = 'UPDATE_CONTROLADOR_ERROR';

export const DELETE_CONTROLADOR_PENDING = 'DELETE_CONTROLADOR_PENDING';
export const DELETE_CONTROLADOR_SUCCESS = 'DELETE_CONTROLADOR_SUCCESS';
export const DELETE_CONTROLADOR_ERROR = 'DELETE_CONTROLADOR_ERROR';
