export const GET_SINIESTRO_PENDING = 'GET_SINIESTRO_PENDING';
export const GET_SINIESTRO_SUCCESS = 'GET_SINIESTRO_SUCCESS';
export const GET_SINIESTRO_ERROR = 'GET_SINIESTRO_ERROR';

export const POST_SINIESTRO_PENDING = 'POST_SINIESTRO_PENDING';
export const POST_SINIESTRO_SUCCESS = 'POST_SINIESTRO_SUCCESS';
export const POST_SINIESTRO_ERROR = 'POST_SINIESTRO_ERROR';

export const UPDATE_SINIESTRO_PENDING = 'UPDATE_SINIESTRO_PENDING';
export const UPDATE_SINIESTRO_SUCCESS = 'UPDATE_SINIESTRO_SUCCESS';
export const UPDATE_SINIESTRO_ERROR = 'UPDATE_SINIESTRO_ERROR';

export const DELETE_SINIESTRO_PENDING = 'DELETE_SINIESTRO_PENDING';
export const DELETE_SINIESTRO_SUCCESS = 'DELETE_SINIESTRO_SUCCESS';
export const DELETE_SINIESTRO_ERROR = 'DELETE_SINIESTRO_ERROR';
