export const GET_LUGARSINIESTRO_PENDING = 'GET_LUGARSINIESTRO_PENDING';
export const GET_LUGARSINIESTRO_SUCCESS = 'GET_LUGARSINIESTRO_SUCCESS';
export const GET_LUGARSINIESTRO_ERROR = 'GET_LUGARSINIESTRO_ERROR';

export const POST_LUGARSINIESTRO_PENDING = 'POST_LUGARSINIESTRO_PENDING';
export const POST_LUGARSINIESTRO_SUCCESS = 'POST_LUGARSINIESTRO_SUCCESS';
export const POST_LUGARSINIESTRO_ERROR = 'POST_LUGARSINIESTRO_ERROR';

export const UPDATE_LUGARSINIESTRO_PENDING = 'UPDATE_LUGARSINIESTRO_PENDING';
export const UPDATE_LUGARSINIESTRO_SUCCESS = 'UPDATE_LUGARSINIESTRO_SUCCESS';
export const UPDATE_LUGARSINIESTRO_ERROR = 'UPDATE_LUGARSINIESTRO_ERROR';

export const DELETE_LUGARSINIESTRO_PENDING = 'DELETE_LUGARSINIESTRO_PENDING';
export const DELETE_LUGARSINIESTRO_SUCCESS = 'DELETE_LUGARSINIESTRO_SUCCESS';
export const DELETE_LUGARSINIESTRO_ERROR = 'DELETE_LUGARSINIESTRO_ERROR';
