export const GET_VEHICLE_PENDING = 'GET_VEHICLE_PENDING';
export const GET_VEHICLE_SUCCESS = 'GET_VEHICLE_SUCCESS';
export const GET_VEHICLE_ERROR = 'GET_VEHICLE_ERROR';

export const ADD_VEHICLE_PENDING = 'ADD_VEHICLE_PENDING';
export const ADD_VEHICLE_SUCCESS = 'ADD_VEHICLE_SUCCESS';
export const ADD_VEHICLE_ERROR = 'ADD_VEHICLE_ERROR';

export const UPDATE_VEHICLE_PENDING = 'UPDATE_VEHICLE_PENDING';
export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS';
export const UPDATE_VEHICLE_ERROR = 'UPDATE_VEHICLE_ERROR';

export const DELETE_VEHICLE_PENDING = 'DELETE_VEHICLE_PENDING';
export const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS';
export const DELETE_VEHICLE_ERROR = 'DELETE_VEHICLE_ERROR';
