export const GET_NOVEDAD_PENDING = 'GET_NOVEDAD_PENDING';
export const GET_NOVEDAD_SUCCESS = 'GET_NOVEDAD_SUCCESS';
export const GET_NOVEDAD_ERROR = 'GET_NOVEDAD_ERROR';

export const ADD_NOVEDAD_PENDING = 'ADD_NOVEDAD_PENDING';
export const ADD_NOVEDAD_SUCCESS = 'ADD_NOVEDAD_SUCCESS';
export const ADD_NOVEDAD_ERROR = 'ADD_NOVEDAD_ERROR';

export const UPDATE_NOVEDAD_PENDING = 'UPDATE_NOVEDAD_PENDING';
export const UPDATE_NOVEDAD_SUCCESS = 'UPDATE_NOVEDAD_SUCCESS';
export const UPDATE_NOVEDAD_ERROR = 'UPDATE_NOVEDAD_ERROR';

export const DELETE_NOVEDAD_PENDING = 'DELETE_NOVEDAD_PENDING';
export const DELETE_NOVEDAD_SUCCESS = 'DELETE_NOVEDAD_SUCCESS';
export const DELETE_NOVEDAD_ERROR = 'DELETE_NOVEDAD_ERROR';
